data = {
    "cityid": "101070901",
    "date": "2025-08-13",
    "week": "星期三",
    "update_time": "16:16",  # 更新时间
    "city": "阜新",  # 城市名称
    "cityEn": "fuxin",
    "country": "中国",
    "countryEn": "China",
    "wea": "多云",  # 天气情况
    "wea_img": "yun",  # 天气图标
    "tem": "26.8",  # 实况温度
    "tem1": "27",  # 高温(白天温度)
    "tem2": "16",  # 低温(夜间温度)
    "win": "西南风",  # 风向
    "win_speed": "3级",  # 风力
    "win_meter": "15km\\h",  # 风速
    "humidity": "66%",  # 湿度
    "visibility": "30km",  # 能见度
    "pressure": "988",  # 气压
    "air": "39",  # 空气质量
    "air_pm25": "10",  # pm2.5
    "air_level": "优",  # 空气质量等级
    "air_tips": "空气质量令人满意，基本无空气污染。",
    "alarm": [  # 气象预警列表
        {
            "alarm_type": "雷电",  # 预警类型
            "alarm_level": "黄色",  # 预警级别
            "alarm_title": "辽宁省阜新市发布雷电黄色预警",  # 预警标题
            "alarm_content": "继续发布雷电黄色预警信号：预计13日白天，阜新市区将出现雷电天气，同时可能伴有短时大风、冰雹、短时强降水等强对流天气，请不要在树下、电杆下、塔吊下避雨，尽量避免户外活动。阜新市气象台2025年08月13日08时08分发布（预警信息来源：国家预警信息发布中心）"
            # 预警内容
        },
        {
            "alarm_type": "雷电",
            "alarm_level": "黄色",
            "alarm_title": "辽宁省阜新市发布雷电黄色预警",
            "alarm_content": "继续发布雷电黄色预警信号：预计13日白天，阜新市区将出现雷电天气，同时可能伴有短时大风、冰雹、短时强降水等强对流天气，请不要在树下、电杆下、塔吊下避雨，尽量避免户外活动。阜新市气象台2025年08月13日08时08分发布（预警信息来源：国家预警信息发布中心）",
        },
    ],
    "rain_pcpn": "6.7",  # 降雨量数值
    "uvIndex": "6",  # 紫外线
    "uvDescription": "强",
    "wea_day": "小到中雨",  # 白天天气情况
    "wea_day_img": "yu",
    "wea_night": "晴",  # 夜间天气情况
    "wea_night_img": "qing",
    "sunrise": "04:59",  # 日出时间
    "sunset": "18:57",  # 日落时间
    "hours": [
        {
            "hours": "17:00",
            "wea": "晴",
            "wea_img": "qing",
            "tem": "26",  # 温度
            "win": "西南风",
            "win_speed": "3级",
            "vis": "19.05",  # 能见度
            "aqinum": "37",  # 空气质量
            "aqi": "优",
        },
        {
            "hours": "18:00",
            "wea": "晴",
            "wea_img": "qing",
            "tem": "25",
            "win": "西南风",
            "win_speed": "1级",
            "vis": "20.01",
            "aqinum": "36",
            "aqi": "优",
        },
        {
            "hours": "19:00",
            "wea": "多云",
            "wea_img": "yun",
            "tem": "23",
            "win": "西南风",
            "win_speed": "1级",
            "vis": "18.83",
            "aqinum": "35",
            "aqi": "优",
        },
        {
            "hours": "20:00",
            "wea": "多云",
            "wea_img": "yun",
            "tem": "23",
            "win": "西南风",
            "win_speed": "1级",
            "vis": "15.65",
            "aqinum": "34",
            "aqi": "优",
        },
        {
            "hours": "21:00",
            "wea": "晴",
            "wea_img": "qing",
            "tem": "22",
            "win": "西南风",
            "win_speed": "1级",
            "vis": "9.73",
            "aqinum": "32",
            "aqi": "优",
        },
        {
            "hours": "22:00",
            "wea": "晴",
            "wea_img": "qing",
            "tem": "22",
            "win": "西风",
            "win_speed": "1级",
            "vis": "9.69",
            "aqinum": "30",
            "aqi": "优",
        },
        {
            "hours": "23:00",
            "wea": "晴",
            "wea_img": "qing",
            "tem": "21",
            "win": "西南风",
            "win_speed": "1级",
            "vis": "9.86",
            "aqinum": "31",
            "aqi": "优",
        },
        {
            "hours": "00:00",
            "wea": "多云",
            "wea_img": "yun",
            "tem": "21",
            "win": "西南风",
            "win_speed": "1级",
            "vis": "8.89",
            "aqinum": "31",
            "aqi": "优",
        },
        {
            "hours": "01:00",
            "wea": "晴",
            "wea_img": "qing",
            "tem": "20",
            "win": "西南风",
            "win_speed": "1级",
            "vis": "10.09",
            "aqinum": "30",
            "aqi": "优",
        },
        {
            "hours": "02:00",
            "wea": "晴",
            "wea_img": "qing",
            "tem": "20",
            "win": "西南风",
            "win_speed": "1级",
            "vis": "16.87",
            "aqinum": "29",
            "aqi": "优",
        },
        {
            "hours": "03:00",
            "wea": "晴",
            "wea_img": "qing",
            "tem": "20",
            "win": "西南风",
            "win_speed": "2级",
            "vis": "24.91",
            "aqinum": "29",
            "aqi": "优",
        },
        {
            "hours": "04:00",
            "wea": "晴",
            "wea_img": "qing",
            "tem": "19",
            "win": "西南风",
            "win_speed": "2级",
            "vis": "29.95",
            "aqinum": "29",
            "aqi": "优",
        },
        {
            "hours": "05:00",
            "wea": "晴",
            "wea_img": "qing",
            "tem": "19",
            "win": "西南风",
            "win_speed": "2级",
            "vis": "27.89",
            "aqinum": "29",
            "aqi": "优",
        },
        {
            "hours": "06:00",
            "wea": "晴",
            "wea_img": "qing",
            "tem": "20",
            "win": "西南风",
            "win_speed": "2级",
            "vis": "25.05",
            "aqinum": "29",
            "aqi": "优",
        },
        {
            "hours": "07:00",
            "wea": "晴",
            "wea_img": "qing",
            "tem": "21",
            "win": "西南风",
            "win_speed": "2级",
            "vis": "24.45",
            "aqinum": "30",
            "aqi": "优",
        },
        {
            "hours": "08:00",
            "wea": "晴",
            "wea_img": "qing",
            "tem": "23",
            "win": "西南风",
            "win_speed": "2级",
            "vis": "29.08",
            "aqinum": "33",
            "aqi": "优",
        },
        {
            "hours": "09:00",
            "wea": "晴",
            "wea_img": "qing",
            "tem": "24",
            "win": "西南风",
            "win_speed": "3级",
            "vis": "33.36",
            "aqinum": "37",
            "aqi": "优",
        },
        {
            "hours": "10:00",
            "wea": "晴",
            "wea_img": "qing",
            "tem": "26",
            "win": "西南风",
            "win_speed": "3级",
            "vis": "38.61",
            "aqinum": "39",
            "aqi": "优",
        },
        {
            "hours": "11:00",
            "wea": "晴",
            "wea_img": "qing",
            "tem": "27",
            "win": "西南风",
            "win_speed": "3级",
            "vis": "37.95",
            "aqinum": "39",
            "aqi": "优",
        },
        {
            "hours": "12:00",
            "wea": "晴",
            "wea_img": "qing",
            "tem": "28",
            "win": "西南风",
            "win_speed": "3级",
            "vis": "34.38",
            "aqinum": "40",
            "aqi": "优",
        },
        {
            "hours": "13:00",
            "wea": "晴",
            "wea_img": "qing",
            "tem": "29",
            "win": "西南风",
            "win_speed": "3级",
            "vis": "34.63",
            "aqinum": "43",
            "aqi": "优",
        },
        {
            "hours": "14:00",
            "wea": "多云",
            "wea_img": "yun",
            "tem": "29",
            "win": "西南风",
            "win_speed": "2级",
            "vis": "32.02",
            "aqinum": "44",
            "aqi": "优",
        },
        {
            "hours": "15:00",
            "wea": "多云",
            "wea_img": "yun",
            "tem": "29",
            "win": "西风",
            "win_speed": "2级",
            "vis": "31.1",
            "aqinum": "45",
            "aqi": "优",
        },
        {
            "hours": "16:00",
            "wea": "晴",
            "wea_img": "qing",
            "tem": "29",
            "win": "西南风",
            "win_speed": "4级",
            "vis": "22.03",
            "aqinum": "44",
            "aqi": "优",
        },
        {
            "hours": "17:00",
            "wea": "小雨",
            "wea_img": "yu",
            "tem": "28",
            "win": "西南风",
            "win_speed": "3级",
            "vis": "21.43",
            "aqinum": "44",
            "aqi": "优",
        },
    ],
    "aqi": {
        "update_time": "16:24",
        "cityid": "101070901",
        "city": "阜新市",
        "cityEn": "",
        "country": "",
        "countryEn": "",
        "air": "39",
        "air_level": "优",
        "air_tips": "空气质量令人满意，基本无空气污染。",
        "pm25": "10",
        "pm25_desc": "优",
        "pm10": "27",
        "pm10_desc": "优",
        "o3": "122",
        "o3_desc": "",
        "no2": "7",
        "no2_desc": "",
        "so2": "6",
        "so2_desc": "",
        "co": "0.4",
        "co_desc": "",
        "kouzhao": "不用佩戴口罩",
        "yundong": "适宜运动",
        "waichu": "适宜外出",
        "kaichuang": "适宜开窗",
        "jinghuaqi": "不需要打开",
    },
    "nums": 3,  # 接口当日请求次数
}
print(data.get("aqi").get("waichu"))
